package tsd.jason.services;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "UserInfoDelegate", targetNamespace = "http://Services.Jason.TSD/")
public interface UserInfoDelegate {

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetUserInfo")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "GetUserInfo", targetNamespace = "http://Services.Jason.TSD/", className = "tsd.jason.services.GetUserInfo")
	@ResponseWrapper(localName = "GetUserInfoResponse", targetNamespace = "http://Services.Jason.TSD/", className = "tsd.jason.services.GetUserInfoResponse")
	public String getUserInfo();

}
